config/routes.rb
Rails.application.routes.draw do
  root to: "lists#index"
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [ :new, :create,]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :list, uniqueness: { scope: :movie }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, :overview, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @bookmark = Bookmark.new()
    @list = List.find(params[:list_id])
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@bookmark.list)
    else
      @list = List.find(params[:list_id])
      render :new
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end
end

def bookmark_params
  params.require(:bookmark).permit(:comment, :movie_id)
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end



  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/bookmarks/new.html.erb
<div class="container">
  <h1>WHAT ADD NAO?</h1>
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.input :comment %>
    <%= f.association :movie %>
    <%= f.submit %>
  <% end %>
</div>
<div class="btn btn-flat">
  <%= link_to "Go Home", root_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Add List", new_list_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <%= link_to "Add List", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%#= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
        <%# else %>
        <!--li class="nav-item"-->
        <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
        <!--/li-->
        <%# end %>
      </ul>
    </div>
  </div>
</div>

app/views/lists/index.html.erb
<%# <%= render "navbar" %>
<div class="banner" style=>
  <div class="container">
    <h1>Make some lists of <strong>movies</strong> to <strong>impress your friends</strong>!</h1>
    <h2>Because one day someone will be like "Did you see that one film with that guy in?" and you'll be all like "Umm, I think so maybe?"</h2>
    <p>And then you can go home and add it to a list on here to remind yourself to watch it sometime or maybe just look at the reviews and pretend to you've seen it because, y'know, you don't wanna look stupid if the topic ever comes up again.</p>
    <div class="btn btn-flat">
      <p> <%= link_to "New List", new_list_path %></p>
    </div>
  </div>
</div>
<div class="wrapper">
  <div class="container mt-3 mb-5">
    <div class="cards">
      <% @lists.each do |list|  %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= list.photo.attached? ? cl_image_path(list.photo.key) : asset_path("movies.jpg") %>')">
          <%= link_to list.name, list_path(list)   %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container, mt-5">
  <h1>NEW LIST</h1>
  <%= simple_form_for @list do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <div class="btn btn-flat">
      <%= f.submit %>
    </div>
  <% end %>
</div>
<div class="btn btn-flat">
  <%= link_to "Go Home", root_path %>
</div>

app/views/lists/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= @list.photo.attached? ? cl_image_path(@list.photo.key) : asset_path("movies.jpg") %>')">
  <div class="container">
    <h1><%= @list.name %></h1>
    <div class="btn btn-flat">
      <%= link_to "Add some crap bruv", new_list_bookmark_path(@list.id) %>
    </div>
  </div>
</div>
</div>
<% @list.movies.each do |movie| %>
  <div class="card" style="width: 18rem;">
    <%= image_tag(movie.poster_url) %>
    <h5 class="card-title"><%= movie.title %></h5>
    <p class="card-text"><%= movie.overview %></p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item"><%= movie.rating %></li>
    <li class="list-group-item">Thats a rating up there.</li>
    <li class="list-group-item">Not just a random number...</li>
  </ul>
</div>
<% end %>
</div>
<div class="btn btn-flat">
  <%= link_to "Delete dis boi", bookmark_path, method: :delete, data: {confirm: "Remove dis list?"} %>
</div>
<div class="btn btn-flat">
  <%= link_to "Go Home", root_path %>
</div>